package transgenic.lauterbrunnen.lateral.entity.generator;

//DO NOT MODIFY, this class was generated by xxx 

import transgenic.lauterbrunnen.lateral.domain.*;

import java.io.Serializable;
import java.util.Collection;

public class CassandraTestObjectImpl implements CassandraTestObject {
    @Transient
    private boolean loadedFromStore=false;
    public boolean loadedFromStore() { return loadedFromStore; }
    public void setLoadedFromStore(boolean loadedFromStore) { this.loadedFromStore = loadedFromStore; }
    private long updateId;
    public void setUpdateId(long updateId) { this.updateId = updateId; }
    public long getUpdateId() { return this.updateId; }

    private transgenic.lauterbrunnen.lateral.domain.UniqueId id;
    private int number;
    private double fraction;
    private float percentage;
    private java.math.BigDecimal decimal;
    private String description;
    private java.util.List<String> reviews;
    private java.util.List<Integer> stars;
    private java.util.Map<UniqueId,String> lookup;
    private java.util.Set<Double> proportions;
    private java.util.Map<UniqueId,java.util.List<String>> contacts;

    public transgenic.lauterbrunnen.lateral.domain.UniqueId getRepositoryId() {
        return getId();
    }

    public EntityReference<CassandraTestObjectImpl> getReference() {
        return null;
    }

    @Override
    public transgenic.lauterbrunnen.lateral.domain.UniqueId getId() {
        return this.id;
    }

    @Override
    public void setId(transgenic.lauterbrunnen.lateral.domain.UniqueId id) {
        this.id = id;
    }

    @Override
    public int getNumber() {
        return this.number;
    }

    @Override
    public void setNumber(int number) {
        this.number = number;
    }

    @Override
    public double getFraction() {
        return this.fraction;
    }

    @Override
    public void setFraction(double fraction) {
        this.fraction = fraction;
    }

    @Override
    public float getPercentage() {
        return this.percentage;
    }

    @Override
    public void setPercentage(float percentage) {
        this.percentage = percentage;
    }

    @Override
    public java.math.BigDecimal getDecimal() {
        return this.decimal;
    }

    @Override
    public void setDecimal(java.math.BigDecimal decimal) {
        this.decimal = decimal;
    }

    @Override
    public String getDescription() {
        return this.description;
    }

    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public java.util.List<String> getReviews() {
        return this.reviews;
    }

    @Override
    public void setReviews(java.util.List<String> reviews) {
        this.reviews = reviews;
    }

    @Override
    public java.util.List<Integer> getStars() {
        return this.stars;
    }

    @Override
    public void setStars(java.util.List<Integer> stars) {
        this.stars = stars;
    }

    @Override
    public java.util.Map<UniqueId,String> getLookup() {
        return this.lookup;
    }

    @Override
    public void setLookup(java.util.Map<UniqueId,String> lookup) {
        this.lookup = lookup;
    }

    @Override
    public java.util.Set<Double> getProportions() {
        return this.proportions;
    }

    @Override
    public void setProportions(java.util.Set<Double> proportions) {
        this.proportions = proportions;
    }

    @Override
    public java.util.Map<UniqueId,java.util.List<String>> getContacts() {
        return this.contacts;
    }

    @Override
    public void setContacts(java.util.Map<UniqueId,java.util.List<String>> contacts) {
        this.contacts = contacts;
    }


    @Override
    public int hashCode() {
        return getRepositoryId() == null ? -1 : getRepositoryId().hashCode();
    }

}
