package transgenic.lauterbrunnen.lateral.entity.generator;

//DO NOT MODIFY, this class was generated by xxx

public interface CassandraTestObject {

    transgenic.lauterbrunnen.lateral.domain.UniqueId getId();

    void setId(transgenic.lauterbrunnen.lateral.domain.UniqueId id);

    int getNumber();

    void setNumber(int number);

    double getFraction();

    void setFraction(double fraction);

    float getPercentage();

    void setPercentage(float percentage);

    java.math.BigDecimal getDecimal();

    void setDecimal(java.math.BigDecimal decimal);

    String getDescription();

    void setDescription(String description);

    java.util.List<String> getReviews();

    void setReviews(java.util.List<String> reviews);

    java.util.List<Integer> getStars();

    void setStars(java.util.List<Integer> stars);

    java.util.Map<transgenic.lauterbrunnen.lateral.domain.UniqueId,String> getLookup();

    void setLookup(java.util.Map<transgenic.lauterbrunnen.lateral.domain.UniqueId, String> lookup);

    java.util.Set<Double> getProportions();

    void setProportions(java.util.Set<Double> proportions);

    java.util.Map<transgenic.lauterbrunnen.lateral.domain.UniqueId,java.util.List<String>> getContacts();

    void setContacts(java.util.Map<transgenic.lauterbrunnen.lateral.domain.UniqueId, java.util.List<String>> contacts);
}
