package transgenic.lauterbrunnen.lateral.persist.hazelcast.generator

import java.lang.reflect.Field

/**
 * Created by stumeikle on 12/06/16.
 */
class GenerateChangeListener extends GeneratePersister{

    public void generate(List<Class> protoclasses, Map<String, Field> idFields) {

        def fn = basePath + "/" + cachePackage.replaceAll("\\.","/") + "/HCCacheChangeManagerImpl.java"; //or connector or what
        println "Writing " + fn;
        def output = new File(fn);

        output << "package " + cachePackage + ";" << System.lineSeparator()
        output << "" << System.lineSeparator();
        output << "//DO NOT MODIFY, this class was generated by xxx " << System.lineSeparator();
        output << ""<< System.lineSeparator();

        output << "import com.hazelcast.core.IMap;" << System.lineSeparator() +
                "import " << implPackage << ".*;" << System.lineSeparator() +
//                "import transgenic.lauterbrunnen.lateral.admin.CommandHandler;"<< System.lineSeparator() +
                "import transgenic.lauterbrunnen.lateral.cache.hazelcast.CacheChangeListener;" << System.lineSeparator() +
                "import transgenic.lauterbrunnen.lateral.cache.hazelcast.HCCacheChangeManager;"<< System.lineSeparator() +
                "import transgenic.lauterbrunnen.lateral.di.DefaultImpl;"<< System.lineSeparator() +
                "import static transgenic.lauterbrunnen.lateral.di.ApplicationDI.inject;"<< System.lineSeparator() +
                "" << System.lineSeparator() +
                "import java.util.Map;" << System.lineSeparator();
        output << "" << System.lineSeparator()
        output << "@DefaultImpl" << System.lineSeparator()
        output << "public class HCCacheChangeManagerImpl implements HCCacheChangeManager {" << System.lineSeparator()
        output << "" << System.lineSeparator();
        output << "    public void initialise( Map<String, IMap> iMapMap ) {" << System.lineSeparator()

        for (Class proto: protoclasses) {
            String idField = idFields.get(proto.getName());
            String lcentity = proto.getSimpleName().substring(0,1) + proto.getSimpleName().substring(1);
            
            output << "        " << proto.getSimpleName() << "Persister " << lcentity << "Persister = inject(" << proto.getSimpleName() << "Persister.class);" << System.lineSeparator +
                    "        if (" << lcentity << "Persister==null) " << lcentity << "Persister = new " << proto.getSimpleName() << "PersisterImplDirect();" << System.lineSeparator
            output << "        iMapMap.get(\"" << proto.getSimpleName() << "\").addEntryListener(" << System.lineSeparator() +
                    "                new CacheChangeListener<" << proto.getSimpleName() << "Impl, " << idField <<">(" << System.lineSeparator() +
                    "                " << lcentity << "Persister), true);"<< System.lineSeparator()
        }
        
        output << "    }" << System.lineSeparator()

        output << "" << System.lineSeparator()

        //Admin bus removed 20190601
//        output << "    public void initAdminEndpoints( CommandHandler handler ) {"<< System.lineSeparator()
//
//        for (Class proto: protoclasses) {
//            output << "        new " << proto.getSimpleName() << "AdminEndpoint(handler);" << System.lineSeparator();
//        }
//        output << "    }" << System.lineSeparator();
        output << "}" << System.lineSeparator()

    }
}
